@host = localhost:7266

GET https://{{host}}/customers
Accept: application/json

###
@customerId=a1d82285-cf45-4e2f-839e-7ffcf971b36a
GET https://{{host}}/customers/{{customerId}}
Accept: application/json

###


POST https://{{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "companyName": "Porject 1"
}

###

@customerIdToUpdate=a1d82285-cf45-4e2f-839e-7ffcf971b36a
PUT https://{{host}}/customers/{{customerIdToUpdate}}
Accept: application/json
Content-Type: application/json

{
  "companyName": "Másik hosszú cucc"
}

###

@customerThatDelete=a86a4bbe-e48f-4bae-914c-241a2b8b2afb
DELETE https://{{host}}/customers/{{customerThatDelete}}
Accept: application/json


###

GET https//{{host}}/brewcoffee
